#!/usr/bin/env python3
"""Regenerate INVENTORY.md from GitHub: latest release assets (authoritative sizes) plus the one-line
descriptions in each repo's README. Needs the `gh` CLI, signed in.   Usage: tools/gen_inventory.py > INVENTORY.md"""
import base64, json, re, subprocess, sys

OWNER = "djayuffe"

def gh(*args):
    return subprocess.run(["gh", *args], capture_output=True, text=True, check=True).stdout

def readme(repo):
    return base64.b64decode(gh("api", f"repos/{OWNER}/{repo}/contents/README.md", "--jq", ".content")).decode()

def release(repo):
    out = gh("release", "list", "-R", f"{OWNER}/{repo}", "--limit", "1", "--json", "tagName,publishedAt")
    rel = json.loads(out)
    if not rel: return None
    tag = rel[0]["tagName"]
    assets = json.loads(gh("release", "view", tag, "-R", f"{OWNER}/{repo}", "--json", "assets"))["assets"]
    return tag, rel[0]["publishedAt"][:10], {a["name"]: a["size"] for a in assets if a["name"].upper().endswith(".COM")}

def clean(t):
    t = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", t)         # strip links
    t = t.replace("|", "/").replace("**", "").strip()
    return t

# repo, kind, how its README lists programs (regex with groups name, description) or None for a single program
REPOS = [
    ("uber10-dos-demo",    "single",     "a 10-byte ASCII scroller with sound"),
    ("uber128-dos-demo",   "single",     "rainbow rings flowing out of the screen centre"),
    ("uber256-dos-intro",  "single",     "two ring families, one orbiting the other, XORed into a moire"),
    ("uber256-rotozoomer", "single",     "an XOR rotozoomer with no multiplies and no sine table"),
    ("uber256-lab",        "collection", r"^\|\s*\[`(\w+)\.COM`\]\([^)]*\)\s*\|\s*\d+ B\s*\|[^|]*\|\s*(.+?)\s*\|\s*$"),
    ("uber-micro-demos",   "collection", r"^\|\s*\*\*(\w+)\*\*\s*\|\s*\d+\s*\|\s*(.+?)\s*\|\s*$"),
    ("uber40k-dos-demo",   "show",       "20-scene show: 3D engine, starfield, scroller, Sound Blaster FM music"),
]
LEGACY = [("uber256-megademo", "the earlier 18-scene line of the big show, superseded by uber40k-dos-demo"),
          ("uber-tiny-demos", "this index; releases v1.0.0 and v1.1.0 still carry the first 5 / 79 / 171-byte binaries")]

progs, repos = [], []
for repo, kind, how in REPOS:
    rel = release(repo)
    if not rel:
        print(f"warning: {repo} has no release", file=sys.stderr); continue
    tag, date, files = rel
    repos.append((repo, kind, tag, date, len(files)))
    descs = {}
    if kind == "collection":
        for line in readme(repo).splitlines():
            m = re.match(how, line)
            if m: descs[m.group(1).upper()] = clean(m.group(2))
    for name, size in sorted(files.items(), key=lambda kv: (kv[1], kv[0])):
        key = name[:-4].upper()
        d = descs.get(key) or (how if kind != "collection" else "")
        if kind == "collection" and not descs.get(key): print(f"warning: no description for {name} in {repo}", file=sys.stderr)
        progs.append((size, name, repo, d))

progs.sort(key=lambda p: (p[0], p[1]))
out = ["# Inventory", "",
       "Generated by `tools/gen_inventory.py` from the **latest GitHub release** of each repository (sizes are the released `.COM` files'),",
       "so it can be refreshed after any release: `tools/gen_inventory.py > INVENTORY.md`.", ""]
out += [f"**{len(progs)} programs in {len(repos)} repositories.** "
        f"{sum(1 for p in progs if p[0] < 9)} are under 9 bytes, {sum(1 for p in progs if p[0] <= 256)} are 256 bytes or less, "
        f"the smallest is {progs[0][1]} ({progs[0][0]} bytes), the largest {progs[-1][1]} ({progs[-1][0]:,} bytes).", ""]
out += ["## Repositories", "", "| Repository | Holds | Latest release | Released | Programs |", "|---|---|---|---|---|"]
for repo, kind, tag, date, n in repos:
    holds = {"single": "one demo", "collection": "a collection", "show": "the big show"}[kind]
    out.append(f"| [{repo}](https://github.com/{OWNER}/{repo}) | {holds} | {tag} | {date} | {n} |")
out += ["", "Also in the family but not counted above (no `.COM` in a current release): " +
        "; ".join(f"[{r}](https://github.com/{OWNER}/{r}) is {w}" for r, w in LEGACY) + ".", "", "## Every program, smallest first", "", "| Bytes | Program | Repository | What it does |", "|---:|---|---|---|"]
for size, name, repo, d in progs:
    out.append(f"| {size:,} | `{name}` | [{repo}](https://github.com/{OWNER}/{repo}) | {d} |")
out += ["", "## Size classes", ""]
bands = [("under 9 bytes", 0, 8), ("9 to 64", 9, 64), ("65 to 128", 65, 128), ("129 to 256", 129, 256), ("over 256", 257, 10**9)]
out += ["| Class | Programs |", "|---|---:|"]
for label, lo, hi in bands:
    out.append(f"| {label} | {sum(1 for p in progs if lo <= p[0] <= hi)} |")
print("\n".join(out))
